const state={all:[],filtered:[],genre:"全部",query:"",view:localStorage.getItem("songlist-view-kira")||"list"};
const el={songList:document.querySelector("#songList"),filters:document.querySelector("#genreFilters"),search:document.querySelector("#searchInput"),random:document.querySelector("#randomBtn"),result:document.querySelector("#resultText"),total:document.querySelector("#totalCount"),empty:document.querySelector("#emptyState"),toast:document.querySelector("#toast"),listBtn:document.querySelector("#listViewBtn"),gridBtn:document.querySelector("#gridViewBtn"),dialog:document.querySelector("#randomDialog"),randomTitle:document.querySelector("#randomTitle"),randomMeta:document.querySelector("#randomMeta"),copyRandom:document.querySelector("#copyRandomBtn"),again:document.querySelector("#againBtn")};
let randomSong=null,toastTimer=null;
const normalize=v=>String(v??"").trim().toLowerCase();
const asArray=v=>Array.isArray(v)?v:(v?[v]:[]);
const songGenres=s=>asArray(s.genre);
const searchable=s=>[s.title,...songGenres(s),s.note].filter(Boolean).join(" ").toLowerCase();
function showToast(t){clearTimeout(toastTimer);el.toast.textContent=t;el.toast.classList.add("show");toastTimer=setTimeout(()=>el.toast.classList.remove("show"),1800)}
async function copyText(t){try{await navigator.clipboard.writeText(t)}catch{const a=document.createElement("textarea");a.value=t;a.style.position="fixed";a.style.opacity="0";document.body.appendChild(a);a.select();document.execCommand("copy");a.remove()}}
async function copySong(s){const t=`点歌 ${s.title}`;await copyText(t);showToast(`已复制：${t}`)}
function badge(t){const s=document.createElement("span");s.className="badge";s.textContent=t;return s}
function renderSongs(){el.songList.innerHTML="";const f=document.createDocumentFragment();for(const s of state.filtered){const b=document.createElement("button");b.type="button";b.className="song";b.setAttribute("aria-label",`复制点歌：${s.title}`);const m=document.createElement("div"),t=document.createElement("div");t.className="song-title";t.textContent=s.title;m.appendChild(t);const sub=document.createElement("div");sub.className="song-sub";songGenres(s).forEach(g=>sub.appendChild(badge(g)));m.appendChild(sub);const c=document.createElement("span");c.className="song-copy";c.textContent="点歌";b.append(m,c);b.addEventListener("click",()=>copySong(s));f.appendChild(b)}el.songList.appendChild(f);el.result.textContent=state.filtered.length===state.all.length?`共 ${state.all.length} 首`:`找到 ${state.filtered.length} / ${state.all.length} 首`;el.empty.hidden=state.filtered.length!==0}
function applyFilters(){const q=normalize(state.query);state.filtered=state.all.filter(s=>(state.genre==="全部"||songGenres(s).includes(state.genre))&&(!q||searchable(s).includes(q)));renderSongs()}
function renderFilters(){const genres=[...new Set(state.all.flatMap(songGenres))].filter(Boolean),preferred=["流行","古风","外语"];genres.sort((a,b)=>{const ai=preferred.indexOf(a),bi=preferred.indexOf(b);if(ai===-1&&bi===-1)return a.localeCompare(b,"zh-CN");if(ai===-1)return 1;if(bi===-1)return -1;return ai-bi});for(const g of ["全部",...genres]){const b=document.createElement("button");b.type="button";b.className=`chip${g===state.genre?" active":""}`;b.textContent=g;b.addEventListener("click",()=>{state.genre=g;[...el.filters.children].forEach(x=>x.classList.toggle("active",x===b));applyFilters()});el.filters.appendChild(b)}}
function setView(v){state.view=v;localStorage.setItem("songlist-view-kira",v);el.songList.classList.toggle("list-view",v==="list");el.songList.classList.toggle("grid-view",v==="grid");el.listBtn.classList.toggle("active",v==="list");el.gridBtn.classList.toggle("active",v==="grid")}
function drawRandom(){if(!state.filtered.length){showToast("当前筛选条件下没有歌曲");return}randomSong=state.filtered[Math.floor(Math.random()*state.filtered.length)];el.randomTitle.textContent=randomSong.title;el.randomMeta.textContent=songGenres(randomSong).join(" · ")||"雪鹤千绪Kira歌单";if(!el.dialog.open)el.dialog.showModal()}
async function init(){try{const r=await fetch("playlist.json",{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();state.all=Array.isArray(d.items)?d.items.filter(x=>x&&x.title):[];state.filtered=[...state.all];el.total.textContent=state.all.length;renderFilters();setView(state.view);applyFilters()}catch(e){console.error(e);el.result.textContent="歌单载入失败";el.empty.hidden=false;el.empty.querySelector("p").textContent="无法读取 playlist.json，请检查文件是否已上传。"}}
el.search.addEventListener("input",e=>{state.query=e.target.value;applyFilters()});el.random.addEventListener("click",drawRandom);el.again.addEventListener("click",drawRandom);el.copyRandom.addEventListener("click",()=>randomSong&&copySong(randomSong));el.listBtn.addEventListener("click",()=>setView("list"));el.gridBtn.addEventListener("click",()=>setView("grid"));init();
